- name: Install Apache
  apt:
    name:
      - apache2
      - unzip
    update_cache: yes
    state: latest

- name: copy index.php file
  copy:
    src: index/index.php
    dest: /var/www/html/index/

- name: restart Apache
  service:
    name: apache2
    enabled: yes
    state: restarted
